from __future__ import annotations

DEFAULT_CONF_THRESHOLD = 0.25
DEFAULT_CURVE_CONF_THRESHOLD = 0.001
DEFAULT_IOU_ASSOCIATION_THRESHOLD = 0.5
DEFAULT_MAX_DETECTIONS = 5000
DEFAULT_DIAGNOSTIC_MAX_DETECTIONS = 5000
FASTER_RCNN_EXPORT_MAX_DETECTIONS = 10000
